//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatSach
    {
        public int MaDatSach { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> MaDocGia { get; set; }
        public Nullable<System.DateTime> NgayDatSach { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        public virtual DocGia DocGia { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
