//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        public DocGia()
        {
            this.DatSaches = new HashSet<DatSach>();
            this.MuonSaches = new HashSet<MuonSach>();
            this.PhatTreHans = new HashSet<PhatTreHan>();
            this.ThanhToanPhats = new HashSet<ThanhToanPhat>();
        }
    
        public int MaDocGia { get; set; }
        public string HoDocGia { get; set; }
        public string TenDocGia { get; set; }
        public Nullable<System.DateTime> NgayThamGia { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        public virtual ICollection<DatSach> DatSaches { get; set; }
        public virtual ICollection<MuonSach> MuonSaches { get; set; }
        public virtual ICollection<PhatTreHan> PhatTreHans { get; set; }
        public virtual ICollection<ThanhToanPhat> ThanhToanPhats { get; set; }
    }
}
