//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuonSach
    {
        public MuonSach()
        {
            this.PhatTreHans = new HashSet<PhatTreHan>();
        }
    
        public int MaMuonSach { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> MaDocGia { get; set; }
        public Nullable<System.DateTime> NgayMuonSach { get; set; }
        public Nullable<System.DateTime> NgayTraSach { get; set; }
    
        public virtual DocGia DocGia { get; set; }
        public virtual Sach Sach { get; set; }
        public virtual ICollection<PhatTreHan> PhatTreHans { get; set; }
    }
}
