//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public Sach()
        {
            this.DatSaches = new HashSet<DatSach>();
            this.MuonSaches = new HashSet<MuonSach>();
            this.TacGias = new HashSet<TacGia>();
        }
    
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> MaTheLoai { get; set; }
        public Nullable<System.DateTime> NamXuatBan { get; set; }
        public Nullable<int> SoLuongSach { get; set; }
        public string AnhBia { get; set; }
    
        public virtual ICollection<DatSach> DatSaches { get; set; }
        public virtual ICollection<MuonSach> MuonSaches { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        public virtual ICollection<TacGia> TacGias { get; set; }
    }
}
