//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheLoai
    {
        public TheLoai()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        public int MaTheLoai { get; set; }
        public string TenTheLoai { get; set; }
    
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
